##legacy method used for hashtag. it's hideous

#most mentioned users | $mentioned_users
s <- separate(s, col = mentioned_users, into = c("mention1", "mention2", "mention3", "mention4", "mention5", "mention6", "mention7", "mention8", "mention9", "mention10", "mention11", "mention12", "mention13", "mention14"), sep = ";", extra = "merge", fill = "right")
mentions <- plyr::count(s$mention1)
mentions <- plyr::rename(mentions,c("freq" = "mention1"))
m2 <- plyr::count(s$mention2)
m2 <- plyr::rename(m2,c("freq" = "mention2"))
mentions <- merge(mentions, m2, by="x", all=TRUE)
m3 <- plyr::count(s$mention3)
m3 <- plyr::rename(m3,c("freq" = "mention3"))
mentions <- merge(mentions, m3, by="x", all=TRUE)
m4 <- plyr::count(s$mention4)
m4 <- plyr::rename(m4,c("freq" = "mention4"))
mentions <- merge(mentions, m4, by="x", all=TRUE)
m5 <- plyr::count(s$mention5)
m5 <- plyr::rename(m5,c("freq" = "mention5"))
mentions <- merge(mentions, m5, by="x", all=TRUE)
m6 <- plyr::count(s$mention6)
m6 <- plyr::rename(m6,c("freq" = "mention6"))
mentions <- merge(mentions, m6, by="x", all=TRUE)
m7 <- plyr::count(s$mention7)
m7 <- plyr::rename(m7,c("freq" = "mention7"))
mentions <- merge(mentions, m7, by="x", all=TRUE)
m8 <- plyr::count(s$mention8)
m8 <- plyr::rename(m8,c("freq" = "mention8"))
mentions <- merge(mentions, m8, by="x", all=TRUE)
m9 <- plyr::count(s$mention9)
m9 <- plyr::rename(m9,c("freq" = "mention9"))
mentions <- merge(mentions, m9, by="x", all=TRUE)
m10 <- plyr::count(s$mention10)
m10 <- plyr::rename(m10,c("freq" = "mention10"))
mentions <- merge(mentions, m10, by="x", all=TRUE)
m11 <- plyr::count(s$mention11)
m11 <- plyr::rename(m11,c("freq" = "mention11"))
mentions <- merge(mentions, m11, by="x", all=TRUE)
m12 <- plyr::count(s$mention12)
m12 <- plyr::rename(m12,c("freq" = "mention12"))
mentions <- merge(mentions, m12, by="x", all=TRUE)
m13 <- plyr::count(s$mention13)
m13 <- plyr::rename(m13,c("freq" = "mention13"))
mentions <- merge(mentions, m13, by="x", all=TRUE)
m14 <- plyr::count(s$mention14)
m14<- plyr::rename(m14,c("freq" = "mention14"))
mentions <- merge(mentions, m14, by="x", all=TRUE)
mentions$total_mentions <- rowSums(mentions[,2:14], na.rm = TRUE)
mentions <- mentions[!is.na(mentions[,1]),]
mentions <- mentions[, c(1,16)]
mentions <- head(arrange(mentions,desc(total_mentions)), n = q)
mentions<<-mentions


#hashtags
s <- separate(s, col = hashes, into = c("hash1", "hash2", "hash3", "hash4", "hash5", "hash6", "hash7", "hash8", "hash9", "hash10", "hash11", "hash12", "hash13", "hash14", "hash15", "hash16", "hash17", "hash18", "hash19", "hash20"), sep = ";", extra = "merge", fill = "right")
hashes <- plyr::count(s$hash1)
hashes <- plyr::rename(hashes,c("freq" = "hash1"))
m2 <- plyr::count(s$hash2)
m2 <- plyr::rename(m2,c("freq" = "hash2"))
hashes <- merge(hashes, m2, by="x", all=TRUE)
m3 <- plyr::count(s$hash3)
m3 <- plyr::rename(m3,c("freq" = "hash3"))
hashes <- merge(hashes, m3, by="x", all=TRUE)
m4 <- plyr::count(s$hash4)
m4 <- plyr::rename(m4,c("freq" = "hash4"))
hashes <- merge(hashes, m4, by="x", all=TRUE)
m5 <- plyr::count(s$hash5)
m5 <- plyr::rename(m5,c("freq" = "hash5"))
hashes <- merge(hashes, m5, by="x", all=TRUE)
m6 <- plyr::count(s$hash6)
m6 <- plyr::rename(m6,c("freq" = "hash6"))
hashes <- merge(hashes, m6, by="x", all=TRUE)
m7 <- plyr::count(s$hash7)
m7 <- plyr::rename(m7,c("freq" = "hash7"))
hashes <- merge(hashes, m7, by="x", all=TRUE)
m8 <- plyr::count(s$hash8)
m8 <- plyr::rename(m8,c("freq" = "hash8"))
hashes <- merge(hashes, m8, by="x", all=TRUE)
m9 <- plyr::count(s$hash9)
m9 <- plyr::rename(m9,c("freq" = "hash9"))
hashes <- merge(hashes, m9, by="x", all=TRUE)
m10 <- plyr::count(s$hash10)
m10 <- plyr::rename(m10,c("freq" = "hash10"))
hashes <- merge(hashes, m10, by="x", all=TRUE)
m11 <- plyr::count(s$hash11)
m11 <- plyr::rename(m11,c("freq" = "hash11"))
hashes <- merge(hashes, m11, by="x", all=TRUE)
m12 <- plyr::count(s$hash12)
m12 <- plyr::rename(m12,c("freq" = "hash12"))
hashes <- merge(hashes, m12, by="x", all=TRUE)
m13 <- plyr::count(s$hash13)
m13 <- plyr::rename(m13,c("freq" = "hash13"))
hashes <- merge(hashes, m13, by="x", all=TRUE)
m14 <- plyr::count(s$hash14)
m14<- plyr::rename(m14,c("freq" = "hash14"))
hashes <- merge(hashes, m14, by="x", all=TRUE)
m15 <- plyr::count(s$hash15)
m15 <- plyr::rename(m15,c("freq" = "hash15"))
hashes <- merge(hashes, m15, by="x", all=TRUE)
m16 <- plyr::count(s$hash16)
m16 <- plyr::rename(m16,c("freq" = "hash16"))
hashes <- merge(hashes, m16, by="x", all=TRUE)
m17 <- plyr::count(s$hash17)
m17 <- plyr::rename(m17,c("freq" = "hash17"))
hashes <- merge(hashes, m17, by="x", all=TRUE)
m18 <- plyr::count(s$hash18)
m18 <- plyr::rename(m18,c("freq" = "hash18"))
hashes <- merge(hashes, m18, by="x", all=TRUE)
m19 <- plyr::count(s$hash19)
m19 <- plyr::rename(m19,c("freq" = "hash19"))
hashes <- merge(hashes, m19, by="x", all=TRUE)
m20 <- plyr::count(s$hash20)
m20 <- plyr::rename(m20,c("freq" = "hash20"))
hashes <- merge(hashes, m20, by="x", all=TRUE)
hashes$total_hashes <- rowSums(hashes[,2:20], na.rm = TRUE)
hashes <- hashes[!is.na(hashes[,1]),]
hashes <- hashes[, c(1,22)]
hashes <- head(arrange(hashes,desc(total_hashes)), n = q)
hashes<<-hashes